apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: gpt-j-isvc
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    #apiVersion: serving.kserve.io/v1alpha2
    serviceAccountName: sa
    #timeout: 240
    model:
      modelFormat:
        name: pytorch
      runtime: tgis-runtime-grpc
      storageUri: s3://mlperf-inference-models/gpt-j-cnn/