apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: "true"
metadata:
  annotations:
    openshift.io/display-name: vLLM
  name: vllm
spec:
  builtInAdapter:
    modelLoadingTimeoutMillis: 90000
  containers:
    - args:
        - --model
        - /mnt/models/
        - --download-dir
        - /models-cache
        - --port
        - "8080"
        - --dtype
        - float16
      image: quay.io/rh-aiservices-bu/vllm-openai-ubi9:0.3.1-fix-2939
      name: kserve-container
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
      resources: # configure as required
        requests:
          cpu: 24
          memory: 128Gi
          nvidia.com/gpu: 1
        limits:
          cpu: 24
          memory: 128Gi
          nvidia.com/gpu: 1
      volumeMounts:
      - mountPath: /dev/shm
        name: dshm
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: pytorch